### PR TITLE
Add private repos support

### PR DESCRIPTION
**Pull request by goneflyin**
As discussed on Slack, here's an extension to the EDIP build container that will copy the SSH keys from /root/ssh to /root/.ssh if that volume has been mapped. 

This change is in support of another PR you'll receive shortly against asaaki/mix-edip.

### CODE REVIEW

**Comment by asaaki** [comment]
Looks good.

For the future try to propose a new version as following:
Copy the previous version directory over to the desired new version instead of just moving/renaming it.
Therefore I don't need to tag and adjust the automated builds for the current version.
(Not a big deal, but less stuff to think about.)

For the EDIP tool it was not a big issue because it is in the end of the build chain for the Docker Hub.

**Comment by goneflyin** [comment]
Sure, I'd be happy to do so. In fact, I _think_ I started that way, but then the diff didn't display what had changed, only that there was a whole lot of new files. I also thought the version history of the files was lost, which isn't normally desirable.

**Comment by goneflyin** [comment]
(Whoops! didn't mean to hit 'return'...)

**Comment by goneflyin** [comment]
(AGAIN! Drat, it's alt-return, not ctrl-return -- I always forget)

Regardless, for future changes in this repo for docker-images, I'll be sure to do the copy-and-edit workflow instead! Thanks for merging!

**Comment by asaaki** [comment]
You're welcome, and your Enter key's also very welcome! :smirk:

**Pull request merged**
